apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-prod
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv-postgres