apiVersion: v1
kind: Secret
metadata:
  name: postgres-prod-secrets
  labels:
    app: postgres-prod
data:
  POSTGRES_DB: bmV3cw==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: bm90YXBvc3RncmVz