apiVersion: v1
kind: Service
metadata:
  name: front-srv
spec:
  selector:
    app: prod-front-pods
  ports:
    - name: front-http
      protocol: TCP
      port: 8000
      targetPort: 80